<?php	$country["AFG"]= Array( "iso2" => "AF", "name" => "Afghanistan, Islamic Republic ");
		$country["ALA"]= Array( "iso2" => "AX", "name" => "Åland Islands");
		$country["ALB"]= Array( "iso2" => "AL", "name" => "Albania, Republic of");
		$country["DZA"]= Array( "iso2" => "DZ", "name" => "Algeria, People's Democratic Republic");
		$country["ASM"]= Array( "iso2" => "AS", "name" => "American Samoa");
		$country["AND"]= Array( "iso2" => "AD", "name" => "Andorra, Principality of");
		$country["AGO"]= Array( "iso2" => "AO", "name" => "Angola, Republic of");
		$country["AIA"]= Array( "iso2" => "AI", "name" => "Anguilla");
		$country["ATA"]= Array( "iso2" => "AQ", "name" => "Antarctica (the territory Sout");
		$country["ATG"]= Array( "iso2" => "AG", "name" => "Antigua and Barbuda");
		$country["ARG"]= Array( "iso2" => "AR", "name" => "Argentina, Argentine Republic");
		$country["ARM"]= Array( "iso2" => "AM", "name" => "Armenia, Republic of");
		$country["ABW"]= Array( "iso2" => "AW", "name" => "Aruba");
		$country["AUS"]= Array( "iso2" => "AU", "name" => "Australia, Commonwealth of");
		$country["AUT"]= Array( "iso2" => "AT", "name" => "Austria, Republic of");
		$country["AZE"]= Array( "iso2" => "AZ", "name" => "Azerbaijan, Republic of");
		$country["BHS"]= Array( "iso2" => "BS", "name" => "Bahamas, Commonwealth of the");
		$country["BHR"]= Array( "iso2" => "BH", "name" => "Bahrain, Kingdom of");
		$country["BGD"]= Array( "iso2" => "BD", "name" => "Bangladesh, People's Republic ");
		$country["BRB"]= Array( "iso2" => "BB", "name" => "Barbados");
		$country["BLR"]= Array( "iso2" => "BY", "name" => "Belarus, Republic of");
		$country["BEL"]= Array( "iso2" => "BE", "name" => "Belgium, Kingdom of");
		$country["BLZ"]= Array( "iso2" => "BZ", "name" => "Belize");
		$country["BEN"]= Array( "iso2" => "BJ", "name" => "Benin, Republic of");
		$country["BMU"]= Array( "iso2" => "BM", "name" => "Bermuda");
		$country["BTN"]= Array( "iso2" => "BT", "name" => "Bhutan, Kingdom of");
		$country["BOL"]= Array( "iso2" => "BO", "name" => "Bolivia, Republic of");
		$country["BIH"]= Array( "iso2" => "BA", "name" => "Bosnia and Herzegovina");
		$country["BWA"]= Array( "iso2" => "BW", "name" => "Botswana, Republic of");
		$country["BVT"]= Array( "iso2" => "BV", "name" => "Bouvet Island (Bouvetoya)");
		$country["BRA"]= Array( "iso2" => "BR", "name" => "Brazil, Federative Republic of");
		$country["IOT"]= Array( "iso2" => "IO", "name" => "British Indian Ocean Territory");
		$country["VGB"]= Array( "iso2" => "VG", "name" => "British Virgin Islands");
		$country["BRN"]= Array( "iso2" => "BN", "name" => "Brunei Darussalam");
		$country["BGR"]= Array( "iso2" => "BG", "name" => "Bulgaria, Republic of");
		$country["BFA"]= Array( "iso2" => "BF", "name" => "Burkina Faso");
		$country["BDI"]= Array( "iso2" => "BI", "name" => "Burundi, Republic of");
		$country["KHM"]= Array( "iso2" => "KH", "name" => "Cambodia, Kingdom of");
		$country["CMR"]= Array( "iso2" => "CM", "name" => "Cameroon, Republic of");
		$country["CAN"]= Array( "iso2" => "CA", "name" => "Canada");
		$country["CPV"]= Array( "iso2" => "CV", "name" => "Cape Verde, Republic of");
		$country["CYM"]= Array( "iso2" => "KY", "name" => "Cayman Islands");
		$country["CAF"]= Array( "iso2" => "CF", "name" => "Central African Republic");
		$country["TCD"]= Array( "iso2" => "TD", "name" => "Chad, Republic of");
		$country["CHL"]= Array( "iso2" => "CL", "name" => "Chile, Republic of");
		$country["CHN"]= Array( "iso2" => "CN", "name" => "China, People's Republic of");
		$country["CXR"]= Array( "iso2" => "CX", "name" => "Christmas Island");
		$country["CCK"]= Array( "iso2" => "CC", "name" => "Cocos (Keeling) Islands");
		$country["COL"]= Array( "iso2" => "CO", "name" => "Colombia, Republic of");
		$country["COM"]= Array( "iso2" => "KM", "name" => "Comoros, Union of the");
		$country["COD"]= Array( "iso2" => "CD", "name" => "Congo, Democratic Republic of ");
		$country["COG"]= Array( "iso2" => "CG", "name" => "Congo, Republic of the");
		$country["COK"]= Array( "iso2" => "CK", "name" => "Cook Islands");
		$country["CRI"]= Array( "iso2" => "CR", "name" => "Costa Rica, Republic of");
		$country["CIV"]= Array( "iso2" => "CI", "name" => "Cote d'Ivoire, Republic of");
		$country["HRV"]= Array( "iso2" => "HR", "name" => "Croatia, Republic of");
		$country["CUB"]= Array( "iso2" => "CU", "name" => "Cuba, Republic of");
		$country["CYP"]= Array( "iso2" => "CY", "name" => "Cyprus, Republic of");
		$country["CZE"]= Array( "iso2" => "CZ", "name" => "Czech Republic");
		$country["DNK"]= Array( "iso2" => "DK", "name" => "Denmark, Kingdom of");
		$country["DJI"]= Array( "iso2" => "DJ", "name" => "Djibouti, Republic of");
		$country["DMA"]= Array( "iso2" => "DM", "name" => "Dominica, Commonwealth of");
		$country["DOM"]= Array( "iso2" => "DO", "name" => "Dominican Republic");
		$country["ECU"]= Array( "iso2" => "EC", "name" => "Ecuador, Republic of");
		$country["EGY"]= Array( "iso2" => "EG", "name" => "Egypt, Arab Republic of");
		$country["SLV"]= Array( "iso2" => "SV", "name" => "El Salvador, Republic of");
		$country["GNQ"]= Array( "iso2" => "GQ", "name" => "Equatorial Guinea, Republic of");
		$country["ERI"]= Array( "iso2" => "ER", "name" => "Eritrea, State of");
		$country["EST"]= Array( "iso2" => "EE", "name" => "Estonia, Republic of");
		$country["ETH"]= Array( "iso2" => "ET", "name" => "Ethiopia, Federal Democratic R");
		$country["FRO"]= Array( "iso2" => "FO", "name" => "Faroe Islands");
		$country["FLK"]= Array( "iso2" => "FK", "name" => "Falkland Islands (Malvinas)");
		$country["FJI"]= Array( "iso2" => "FJ", "name" => "Fiji, Republic of the Fiji Isl");
		$country["FIN"]= Array( "iso2" => "FI", "name" => "Finland, Republic of");
		$country["FRA"]= Array( "iso2" => "FR", "name" => "France, French Republic");
		$country["GUF"]= Array( "iso2" => "GF", "name" => "French Guiana");
		$country["PYF"]= Array( "iso2" => "PF", "name" => "French Polynesia");
		$country["ATF"]= Array( "iso2" => "TF", "name" => "French Southern Territories");
		$country["GAB"]= Array( "iso2" => "GA", "name" => "Gabon, Gabonese Republic");
		$country["GMB"]= Array( "iso2" => "GM", "name" => "Gambia, Republic of the");
		$country["GEO"]= Array( "iso2" => "GE", "name" => "Georgia");
		$country["DEU"]= Array( "iso2" => "DE", "name" => "Germany, Federal Republic of");
		$country["GHA"]= Array( "iso2" => "GH", "name" => "Ghana, Republic of");
		$country["GIB"]= Array( "iso2" => "GI", "name" => "Gibraltar");
		$country["GRC"]= Array( "iso2" => "GR", "name" => "Greece, Hellenic Republic");
		$country["GRL"]= Array( "iso2" => "GL", "name" => "Greenland");
		$country["GRD"]= Array( "iso2" => "GD", "name" => "Grenada");
		$country["GLP"]= Array( "iso2" => "GP", "name" => "Guadeloupe");
		$country["GUM"]= Array( "iso2" => "GU", "name" => "Guam");
		$country["GTM"]= Array( "iso2" => "GT", "name" => "Guatemala, Republic of");
		$country["GGY"]= Array( "iso2" => "GG", "name" => "Guernsey, Bailiwick of");
		$country["GIN"]= Array( "iso2" => "GN", "name" => "Guinea, Republic of");
		$country["GNB"]= Array( "iso2" => "GW", "name" => "Guinea-Bissau, Republic of");
		$country["GUY"]= Array( "iso2" => "GY", "name" => "Guyana, Co-operative Republic ");
		$country["HTI"]= Array( "iso2" => "HT", "name" => "Haiti, Republic of");
		$country["HMD"]= Array( "iso2" => "HM", "name" => "Heard Island and McDonald Isla");
		$country["VAT"]= Array( "iso2" => "VA", "name" => "Holy See (Vatican City State)");
		$country["HND"]= Array( "iso2" => "HN", "name" => "Honduras, Republic of");
		$country["HKG"]= Array( "iso2" => "HK", "name" => "Hong Kong, Special Administrat");
		$country["HUN"]= Array( "iso2" => "HU", "name" => "Hungary, Republic of");
		$country["ISL"]= Array( "iso2" => "IS", "name" => "Iceland, Republic of");
		$country["IND"]= Array( "iso2" => "IN", "name" => "India, Republic of");
		$country["IDN"]= Array( "iso2" => "ID", "name" => "Indonesia, Republic of");
		$country["IRN"]= Array( "iso2" => "IR", "name" => "Iran, Islamic Republic of");
		$country["IRQ"]= Array( "iso2" => "IQ", "name" => "Iraq, Republic of");
		$country["IRL"]= Array( "iso2" => "IE", "name" => "Ireland");
		$country["IMN"]= Array( "iso2" => "IM", "name" => "Isle of Man");
		$country["ISR"]= Array( "iso2" => "IL", "name" => "Israel, State of");
		$country["ITA"]= Array( "iso2" => "IT", "name" => "Italy, Italian Republic");
		$country["JAM"]= Array( "iso2" => "JM", "name" => "Jamaica");
		$country["JPN"]= Array( "iso2" => "JP", "name" => "Japan");
		$country["JEY"]= Array( "iso2" => "JE", "name" => "Jersey, Bailiwick of");
		$country["JOR"]= Array( "iso2" => "JO", "name" => "Jordan, Hashemite Kingdom of");
		$country["KAZ"]= Array( "iso2" => "KZ", "name" => "Kazakhstan, Republic of");
		$country["KEN"]= Array( "iso2" => "KE", "name" => "Kenya, Republic of");
		$country["KIR"]= Array( "iso2" => "KI", "name" => "Kiribati, Republic of");
		$country["PRK"]= Array( "iso2" => "KP", "name" => "Korea, Democratic People's Rep");
		$country["KOR"]= Array( "iso2" => "KR", "name" => "Korea, Republic of");
		$country["KWT"]= Array( "iso2" => "KW", "name" => "Kuwait, State of");
		$country["KGZ"]= Array( "iso2" => "KG", "name" => "Kyrgyz Republic");
		$country["LAO"]= Array( "iso2" => "LA", "name" => "Lao People's Democratic Republ");
		$country["LVA"]= Array( "iso2" => "LV", "name" => "Latvia, Republic of");
		$country["LBN"]= Array( "iso2" => "LB", "name" => "Lebanon, Lebanese Republic");
		$country["LSO"]= Array( "iso2" => "LS", "name" => "Lesotho, Kingdom of");
		$country["LBR"]= Array( "iso2" => "LR", "name" => "Liberia, Republic of");
		$country["LBY"]= Array( "iso2" => "LY", "name" => "Libyan Arab Jamahiriya");
		$country["LIE"]= Array( "iso2" => "LI", "name" => "Liechtenstein, Principality of");
		$country["LTU"]= Array( "iso2" => "LT", "name" => "Lithuania, Republic of");
		$country["LUX"]= Array( "iso2" => "LU", "name" => "Luxembourg, Grand Duchy of");
		$country["MAC"]= Array( "iso2" => "MO", "name" => "Macao, Special Administrative ");
		$country["MKD"]= Array( "iso2" => "MK", "name" => "Macedonia, the former Yugoslav");
		$country["MDG"]= Array( "iso2" => "MG", "name" => "Madagascar, Republic of");
		$country["MWI"]= Array( "iso2" => "MW", "name" => "Malawi, Republic of");
		$country["MYS"]= Array( "iso2" => "MY", "name" => "Malaysia");
		$country["MDV"]= Array( "iso2" => "MV", "name" => "Maldives, Republic of");
		$country["MLI"]= Array( "iso2" => "ML", "name" => "Mali, Republic of");
		$country["MLT"]= Array( "iso2" => "MT", "name" => "Malta, Republic of");
		$country["MHL"]= Array( "iso2" => "MH", "name" => "Marshall Islands, Republic of ");
		$country["MTQ"]= Array( "iso2" => "MQ", "name" => "Martinique");
		$country["MRT"]= Array( "iso2" => "MR", "name" => "Mauritania, Islamic Republic o");
		$country["MUS"]= Array( "iso2" => "MU", "name" => "Mauritius, Republic of");
		$country["MYT"]= Array( "iso2" => "YT", "name" => "Mayotte");
		$country["MEX"]= Array( "iso2" => "MX", "name" => "Mexico, United Mexican States");
		$country["FSM"]= Array( "iso2" => "FM", "name" => "Micronesia, Federated States o");
		$country["MDA"]= Array( "iso2" => "MD", "name" => "Moldova, Republic of");
		$country["MCO"]= Array( "iso2" => "MC", "name" => "Monaco, Principality of");
		$country["MNG"]= Array( "iso2" => "MN", "name" => "Mongolia");
		$country["MNE"]= Array( "iso2" => "ME", "name" => "Montenegro, Republic of");
		$country["MSR"]= Array( "iso2" => "MS", "name" => "Montserrat");
		$country["MAR"]= Array( "iso2" => "MA", "name" => "Morocco, Kingdom of");
		$country["MOZ"]= Array( "iso2" => "MZ", "name" => "Mozambique, Republic of");
		$country["MMR"]= Array( "iso2" => "MM", "name" => "Myanmar, Union of");
		$country["NAM"]= Array( "iso2" => "NA", "name" => "Namibia, Republic of");
		$country["NRU"]= Array( "iso2" => "NR", "name" => "Nauru, Republic of");
		$country["NPL"]= Array( "iso2" => "NP", "name" => "Nepal, State of");
		$country["ANT"]= Array( "iso2" => "AN", "name" => "Netherlands Antilles");
		$country["NLD"]= Array( "iso2" => "NL", "name" => "Netherlands, Kingdom of the");
		$country["NCL"]= Array( "iso2" => "NC", "name" => "New Caledonia");
		$country["NZL"]= Array( "iso2" => "NZ", "name" => "New Zealand");
		$country["NIC"]= Array( "iso2" => "NI", "name" => "Nicaragua, Republic of");
		$country["NER"]= Array( "iso2" => "NE", "name" => "Niger, Republic of");
		$country["NGA"]= Array( "iso2" => "NG", "name" => "Nigeria, Federal Republic of");
		$country["NIU"]= Array( "iso2" => "NU", "name" => "Niue");
		$country["NFK"]= Array( "iso2" => "NF", "name" => "Norfolk Island");
		$country["MNP"]= Array( "iso2" => "MP", "name" => "Northern Mariana Islands, Comm");
		$country["NOR"]= Array( "iso2" => "NO", "name" => "Norway, Kingdom of");
		$country["OMN"]= Array( "iso2" => "OM", "name" => "Oman, Sultanate of");
		$country["PAK"]= Array( "iso2" => "PK", "name" => "Pakistan, Islamic Republic of");
		$country["PLW"]= Array( "iso2" => "PW", "name" => "Palau, Republic of");
		$country["PSE"]= Array( "iso2" => "PS", "name" => "Palestinian Territory, Occupie");
		$country["PAN"]= Array( "iso2" => "PA", "name" => "Panama, Republic of");
		$country["PNG"]= Array( "iso2" => "PG", "name" => "Papua New Guinea, Independent ");
		$country["PRY"]= Array( "iso2" => "PY", "name" => "Paraguay, Republic of");
		$country["PER"]= Array( "iso2" => "PE", "name" => "Peru, Republic of");
		$country["PHL"]= Array( "iso2" => "PH", "name" => "Philippines, Republic of the");
		$country["PCN"]= Array( "iso2" => "PN", "name" => "Pitcairn Islands");
		$country["POL"]= Array( "iso2" => "PL", "name" => "Poland, Republic of");
		$country["PRT"]= Array( "iso2" => "PT", "name" => "Portugal, Portuguese Republic");
		$country["PRI"]= Array( "iso2" => "PR", "name" => "Puerto Rico, Commonwealth of");
		$country["QAT"]= Array( "iso2" => "QA", "name" => "Qatar, State of");
		$country["REU"]= Array( "iso2" => "RE", "name" => "Reunion");
		$country["ROU"]= Array( "iso2" => "RO", "name" => "Romania");
		$country["RUS"]= Array( "iso2" => "RU", "name" => "Russian Federation");
		$country["RWA"]= Array( "iso2" => "RW", "name" => "Rwanda, Republic of");
		$country["BLM"]= Array( "iso2" => "BL", "name" => "Saint Barthelemy");
		$country["SHN"]= Array( "iso2" => "SH", "name" => "Saint Helena");
		$country["KNA"]= Array( "iso2" => "KN", "name" => "Saint Kitts and Nevis, Federat");
		$country["LCA"]= Array( "iso2" => "LC", "name" => "Saint Lucia");
		$country["MAF"]= Array( "iso2" => "MF", "name" => "Saint Martin");
		$country["SPM"]= Array( "iso2" => "PM", "name" => "Saint Pierre and Miquelon");
		$country["VCT"]= Array( "iso2" => "VC", "name" => "Saint Vincent and the Grenadin");
		$country["WSM"]= Array( "iso2" => "WS", "name" => "Samoa, Independent State of");
		$country["SMR"]= Array( "iso2" => "SM", "name" => "San Marino, Republic of");
		$country["STP"]= Array( "iso2" => "ST", "name" => "Sao Tome and Principe, Democra");
		$country["SAU"]= Array( "iso2" => "SA", "name" => "Saudi Arabia, Kingdom of");
		$country["SEN"]= Array( "iso2" => "SN", "name" => "Senegal, Republic of");
		$country["SRB"]= Array( "iso2" => "RS", "name" => "Serbia, Republic of");
		$country["SYC"]= Array( "iso2" => "SC", "name" => "Seychelles, Republic of");
		$country["SLE"]= Array( "iso2" => "SL", "name" => "Sierra Leone, Republic of");
		$country["SGP"]= Array( "iso2" => "SG", "name" => "Singapore, Republic of");
		$country["SVK"]= Array( "iso2" => "SK", "name" => "Slovakia (Slovak Republic)");
		$country["SVN"]= Array( "iso2" => "SI", "name" => "Slovenia, Republic of");
		$country["SLB"]= Array( "iso2" => "SB", "name" => "Solomon Islands");
		$country["SOM"]= Array( "iso2" => "SO", "name" => "Somalia, Somali Republic");
		$country["ZAF"]= Array( "iso2" => "ZA", "name" => "South Africa, Republic of");
		$country["SGS"]= Array( "iso2" => "GS", "name" => "South Georgia and the South Sa");
		$country["ESP"]= Array( "iso2" => "ES", "name" => "Spain, Kingdom of");
		$country["LKA"]= Array( "iso2" => "LK", "name" => "Sri Lanka, Democratic Socialis");
		$country["SDN"]= Array( "iso2" => "SD", "name" => "Sudan, Republic of");
		$country["SUR"]= Array( "iso2" => "SR", "name" => "Suriname, Republic of");
		$country["SJM"]= Array( "iso2" => "SJ", "name" => "Svalbard & Jan Mayen Islands");
		$country["SWZ"]= Array( "iso2" => "SZ", "name" => "Swaziland, Kingdom of");
		$country["SWE"]= Array( "iso2" => "SE", "name" => "Sweden, Kingdom of");
		$country["CHE"]= Array( "iso2" => "CH", "name" => "Switzerland, Swiss Confederati");
		$country["SYR"]= Array( "iso2" => "SY", "name" => "Syrian Arab Republic");
		$country["TWN"]= Array( "iso2" => "TW", "name" => "Taiwan");
		$country["TJK"]= Array( "iso2" => "TJ", "name" => "Tajikistan, Republic of");
		$country["TZA"]= Array( "iso2" => "TZ", "name" => "Tanzania, United Republic of");
		$country["THA"]= Array( "iso2" => "TH", "name" => "Thailand, Kingdom of");
		$country["TLS"]= Array( "iso2" => "TL", "name" => "Timor-Leste, Democratic Republ");
		$country["TGO"]= Array( "iso2" => "TG", "name" => "Togo, Togolese Republic");
		$country["TKL"]= Array( "iso2" => "TK", "name" => "Tokelau");
		$country["TON"]= Array( "iso2" => "TO", "name" => "Tonga, Kingdom of");
		$country["TTO"]= Array( "iso2" => "TT", "name" => "Trinidad and Tobago, Republic ");
		$country["TUN"]= Array( "iso2" => "TN", "name" => "Tunisia, Tunisian Republic");
		$country["TUR"]= Array( "iso2" => "TR", "name" => "Turkey, Republic of");
		$country["TKM"]= Array( "iso2" => "TM", "name" => "Turkmenistan");
		$country["TCA"]= Array( "iso2" => "TC", "name" => "Turks and Caicos Islands");
		$country["TUV"]= Array( "iso2" => "TV", "name" => "Tuvalu");
		$country["UGA"]= Array( "iso2" => "UG", "name" => "Uganda, Republic of");
		$country["UKR"]= Array( "iso2" => "UA", "name" => "Ukraine");
		$country["ARE"]= Array( "iso2" => "AE", "name" => "United Arab Emirates");
		$country["GBR"]= Array( "iso2" => "GB", "name" => "United Kingdom of Great Britain");
		$country["USA"]= Array( "iso2" => "US", "name" => "United States of America");
		$country["UMI"]= Array( "iso2" => "UM", "name" => "United States Minor Outlying I");
		$country["VIR"]= Array( "iso2" => "VI", "name" => "United States Virgin Islands");
		$country["URY"]= Array( "iso2" => "UY", "name" => "Uruguay, Eastern Republic of");
		$country["UZB"]= Array( "iso2" => "UZ", "name" => "Uzbekistan, Republic of");
		$country["VUT"]= Array( "iso2" => "VU", "name" => "Vanuatu, Republic of");
		$country["VEN"]= Array( "iso2" => "VE", "name" => "Venezuela, Bolivarian Republic");
		$country["VNM"]= Array( "iso2" => "VN", "name" => "Vietnam, Socialist Republic of");
		$country["WLF"]= Array( "iso2" => "WF", "name" => "Wallis and Futuna");
		$country["ESH"]= Array( "iso2" => "EH", "name" => "Western Sahara");
		$country["YEM"]= Array( "iso2" => "YE", "name" => "Yemen");
		$country["ZMB"]= Array( "iso2" => "ZM", "name" => "Zambia, Republic of");
		$country["ZWE"]= Array( "iso2" => "ZW", "name" => "Zimbabwe, Republic of");
		$country["0"]= Array( "iso2" => "0", "name" => "NO VALID COUNTRY");
?>
